{
  "openapi": "3.0.3",

  "info": {
    "version": "1.0.11",
    "title": "Swagger Slim Moms - OpenAPI 3.0",
    "description": "All about Slim Moms API"
  },

  "consume": ["application/json"],
  "produces": ["application/json"],

  "servers": [{ "url": "http://localhost:5001" }],

  "tags": [
    {
      "name": "Auth",
      "description": "Auth endpoints"
    },
    {
      "name": "Daily-productі",
      "description": "Daily products for diary page endpoints"
    }
  ],

  "paths": {
    "/api/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",

        "parameters": [],
        "security": [],

        "requestBody": {
          "description": "Registration object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },

        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },

          "404": {
            "description": "Bad request (invalid request bodu)"
          },

          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },

    "/api/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",

        "parameters": [],
        "security": [],

        "requestBody": {
          "description": "Login object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },

          "400": {
            "description": "Invalid username or password supplied"
          }
        }
      }
    },

    "/api/auth/logout": {
      "get": {
        "tags": ["Auth"],
        "summary": "User logout",

        "parameters": [],
        "security": [],

        "requestBody": {
          "description": "logout object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },

          "400": {
            "description": "Invalid username or password supplied"
          }
        }
      }
    },

    "/api/auth/refresh": {
      "post": {
        "tags": ["Auth"],
        "summary": "Refresh token",

        "parameters": [],
        "security": [],

        "requestBody": {
          "description": "Refresh object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": ""
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": ""
                }
              }
            }
          },

          "400": {
            "description": "Invalid username or password supplied"
          }
        }
      }
    },

    "/api/diary": {
      "post": {
        "tags": ["Daily-productі"],
        "summary": "Daily products",

        "parameters": [],
        "security": [],

        "requestBody": {
          "description": "daily products object",
          "required": true,
          "content": {}
        },

        "responses": {
          "201": {
            "description": "test"
          },

          "404": {
            "description": "Bad request (invalid request bodu)"
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": [true],
        "properties": {
          "name": {
            "type": "string",
            "description": "User name",
            "example": "Bob"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "example": "bob@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "example": "1234567"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "response": {
            "type": "string",
            "description": "Status code",
            "data": {
              "user": "user name",
              "email": "user email"
            },
            "example": {
              "status": "Created",
              "code": 201,
              "data": {
                "user": {
                  "name": "asd",
                  "email": "asd1@gmail.com"
                }
              }
            }
          }
        }
      },

      "LoginRequest": {
        "type": "object",
        "required": [true],
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "example": "bob@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "example": "1234567"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "response": {
            "type": "object",
            "description": "Status code",
            "example": {
              "status": "success",
              "code": 200,
              "data": {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2ExNzY2MzkxYjFjODU0ZTQ5Y2MxMjkiLCJzaWQiOiI2M2EzMWNjNTA2NmVjYmYxZmE4NWJmZGMiLCJpYXQiOjE2NzE2MzQxMTcsImV4cCI6MTY3MTYzNzcxN30.3vm1XXMwW-BzQsqVPTBmUqhRlMJbjH9g71wyh5DaVoU",
                "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2ExNzY2MzkxYjFjODU0ZTQ5Y2MxMjkiLCJzaWQiOiI2M2EzMWNjNTA2NmVjYmYxZmE4NWJmZGMiLCJpYXQiOjE2NzE2MzQxMTcsImV4cCI6MTY3MzM2MjExN30.j3hbHqF_7j8gEnfYrV1-7coBy-_yizgUiC779o5n45o",
                "user": {
                  "email": "bob@gmail.com",
                  "name": "Bob"
                }
              }
            }
          }
        }
      },

      "LogoutRequest": {
        "type": "object",
        "required": [true],
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "example": "bob@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "example": "1234567"
          }
        }
      },
      "LogoutResponse": {
        "type": "object",
        "properties": {
          "response": {
            "type": "object",
            "description": "Status code",
            "example": {
              "status": "success",
              "code": 200,
              "data": {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2ExNzY2MzkxYjFjODU0ZTQ5Y2MxMjkiLCJzaWQiOiI2M2EzMWNjNTA2NmVjYmYxZmE4NWJmZGMiLCJpYXQiOjE2NzE2MzQxMTcsImV4cCI6MTY3MTYzNzcxN30.3vm1XXMwW-BzQsqVPTBmUqhRlMJbjH9g71wyh5DaVoU",
                "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2ExNzY2MzkxYjFjODU0ZTQ5Y2MxMjkiLCJzaWQiOiI2M2EzMWNjNTA2NmVjYmYxZmE4NWJmZGMiLCJpYXQiOjE2NzE2MzQxMTcsImV4cCI6MTY3MzM2MjExN30.j3hbHqF_7j8gEnfYrV1-7coBy-_yizgUiC779o5n45o",
                "user": {
                  "email": "bob@gmail.com",
                  "name": "Bob"
                }
              }
            }
          }
        }
      }
    }
  },

  "securitySchemas": {
    "Bearer": {
      "type": "http",
      "schema": "bearer",
      "bearerFormat": "JWT"
    }
  }
}
